default: &default
  adapter: mysql2
  username: root
  password: password@123#
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ecommerence

test:
  <<: *default
  database: ecommerence_test

production:
  <<: *default
  database: ecommerce_production
